# https://taskfile.dev

version: "3"

vars:
  REPOSITORY: ghcr.io/s04/llama-embeddings

tasks:
  run:
    cmds:
      - docker run -it --rm --pull always -p 8000:8000 -v ./.cache:/app/.cache {{.REPOSITORY}}
  build:
    cmds:
      - docker build . -t {{.REPOSITORY}}:latest
      - docker run -it --rm -p 8000:8000 -e MODEL=jinaai/jina-embeddings-v3 {{.REPOSITORY}}:latest

  publish:
    cmds:
      - docker buildx build . --push --platform linux/amd64,linux/arm64 --tag {{.REPOSITORY}}:latest
